#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/gyc/match_ws/devel_isolated/nav_core:/home/gyc/match_ws/devel_isolated/costmap_2d:/home/gyc/match_ws/devel_isolated/voxel_grid:/home/gyc/match_ws/devel_isolated/velodyne_pointcloud:/home/gyc/match_ws/devel_isolated/velodyne_pcl:/home/gyc/match_ws/devel_isolated/velodyne_driver:/home/gyc/match_ws/devel_isolated/velodyne_msgs:/home/gyc/match_ws/devel_isolated/velodyne_laserscan:/home/gyc/match_ws/devel_isolated/velodyne:/home/gyc/match_ws/devel_isolated/slam_gmapping:/home/gyc/match_ws/devel_isolated/simulation_launch:/home/gyc/match_ws/devel_isolated/pointcloud_to_laserscan:/home/gyc/match_ws/devel_isolated/path_rviz_plugin:/home/gyc/match_ws/devel_isolated/path_server:/home/gyc/match_ws/devel_isolated/gmapping:/home/gyc/match_ws/devel_isolated/openslam_gmapping:/home/gyc/match_ws/devel_isolated/navigation:/home/gyc/match_ws/devel_isolated/move_base_flex:/home/gyc/match_ws/devel_isolated/mbf_simple_nav:/home/gyc/match_ws/devel_isolated/mbf_abstract_nav:/home/gyc/match_ws/devel_isolated/mbf_utility:/home/gyc/match_ws/devel_isolated/mbf_msgs:/home/gyc/match_ws/devel_isolated/mbf_abstract_core:/home/gyc/match_ws/devel_isolated/map_server:/home/gyc/match_ws/devel_isolated/location_fusion:/home/gyc/match_ws/devel_isolated/fake_localization:/home/gyc/match_ws/devel_isolated/dashgo_driver:/home/gyc/match_ws/devel_isolated/cartographer_rviz:/home/gyc/match_ws/devel_isolated/cartographer_ros:/home/gyc/match_ws/devel_isolated/cartographer_ros_msgs:/home/gyc/match_ws/devel_isolated/autolabor_test_launch:/home/gyc/match_ws/devel_isolated/autolabor_navigation_launch:/home/gyc/match_ws/devel_isolated/ah100b:/opt/ros/melodic:/home/gyc/match_ws/devel_isolated/cartographer:/home/gyc/match_ws/devel_isolated/ceres-solver'
export LD_LIBRARY_PATH='/home/gyc/match_ws/devel_isolated/nav_core/lib:/home/gyc/match_ws/devel_isolated/costmap_2d/lib:/home/gyc/match_ws/devel_isolated/voxel_grid/lib:/home/gyc/match_ws/devel_isolated/velodyne_pointcloud/lib:/home/gyc/match_ws/devel_isolated/velodyne_pcl/lib:/home/gyc/match_ws/devel_isolated/velodyne_driver/lib:/home/gyc/match_ws/devel_isolated/velodyne_msgs/lib:/home/gyc/match_ws/devel_isolated/velodyne_laserscan/lib:/home/gyc/match_ws/devel_isolated/simulation_launch/lib:/home/gyc/match_ws/devel_isolated/pointcloud_to_laserscan/lib:/home/gyc/match_ws/devel_isolated/path_rviz_plugin/lib:/home/gyc/match_ws/devel_isolated/path_server/lib:/home/gyc/match_ws/devel_isolated/gmapping/lib:/home/gyc/match_ws/devel_isolated/openslam_gmapping/lib:/home/gyc/match_ws/devel_isolated/mbf_simple_nav/lib:/home/gyc/match_ws/devel_isolated/mbf_abstract_nav/lib:/home/gyc/match_ws/devel_isolated/mbf_utility/lib:/home/gyc/match_ws/devel_isolated/mbf_msgs/lib:/home/gyc/match_ws/devel_isolated/mbf_abstract_core/lib:/home/gyc/match_ws/devel_isolated/map_server/lib:/home/gyc/match_ws/devel_isolated/location_fusion/lib:/home/gyc/match_ws/devel_isolated/fake_localization/lib:/home/gyc/match_ws/devel_isolated/dashgo_driver/lib:/home/gyc/match_ws/devel_isolated/cartographer_rviz/lib:/home/gyc/match_ws/devel_isolated/cartographer_ros/lib:/home/gyc/match_ws/devel_isolated/cartographer_ros_msgs/lib:/home/gyc/match_ws/devel_isolated/autolabor_test_launch/lib:/home/gyc/match_ws/devel_isolated/autolabor_navigation_launch/lib:/home/gyc/match_ws/devel_isolated/ah100b/lib:/opt/ros/melodic/lib:/home/gyc/match_ws/devel_isolated/cartographer/lib:/home/gyc/match_ws/devel_isolated/ceres-solver/lib:/usr/local/cuda-10.0/lib64'
export PATH='/opt/ros/melodic/bin:/home/gyc/match_ws/devel_isolated/cartographer/bin:/usr/local/cuda-10.0/bin:/home/gyc/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export PKG_CONFIG_PATH="/home/gyc/match_ws/devel_isolated/nav_core/lib/pkgconfig:$PKG_CONFIG_PATH"
export ROSLISP_PACKAGE_DIRECTORIES="/home/gyc/match_ws/devel_isolated/nav_core/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/gyc/match_ws/src/navigation/nav_core:$ROS_PACKAGE_PATH"