# CMake generated Testfile for 
# Source directory: /home/gyc/match_ws/src/navigation/move_base_flex/mbf_abstract_nav
# Build directory: /home/gyc/match_ws/build_isolated/mbf_abstract_nav
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_mbf_abstract_nav_gtest_mbf_abstract_server_gtest "/home/gyc/match_ws/build_isolated/mbf_abstract_nav/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/gyc/match_ws/build_isolated/mbf_abstract_nav/test_results/mbf_abstract_nav/gtest-mbf_abstract_server_gtest.xml" "--return-code" "/home/gyc/match_ws/devel_isolated/mbf_abstract_nav/lib/mbf_abstract_nav/mbf_abstract_server_gtest --gtest_output=xml:/home/gyc/match_ws/build_isolated/mbf_abstract_nav/test_results/mbf_abstract_nav/gtest-mbf_abstract_server_gtest.xml")
add_test(_ctest_mbf_abstract_nav_rostest_test_abstract_action_base.launch "/home/gyc/match_ws/build_isolated/mbf_abstract_nav/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/gyc/match_ws/build_isolated/mbf_abstract_nav/test_results/mbf_abstract_nav/rostest-test_abstract_action_base.xml" "--return-code" "/usr/bin/python2 /opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/gyc/match_ws/src/navigation/move_base_flex/mbf_abstract_nav --package=mbf_abstract_nav --results-filename test_abstract_action_base.xml --results-base-dir \"/home/gyc/match_ws/build_isolated/mbf_abstract_nav/test_results\" /home/gyc/match_ws/src/navigation/move_base_flex/mbf_abstract_nav/test/abstract_action_base.launch ")
add_test(_ctest_mbf_abstract_nav_rostest_test_abstract_controller_execution.launch "/home/gyc/match_ws/build_isolated/mbf_abstract_nav/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/gyc/match_ws/build_isolated/mbf_abstract_nav/test_results/mbf_abstract_nav/rostest-test_abstract_controller_execution.xml" "--return-code" "/usr/bin/python2 /opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/gyc/match_ws/src/navigation/move_base_flex/mbf_abstract_nav --package=mbf_abstract_nav --results-filename test_abstract_controller_execution.xml --results-base-dir \"/home/gyc/match_ws/build_isolated/mbf_abstract_nav/test_results\" /home/gyc/match_ws/src/navigation/move_base_flex/mbf_abstract_nav/test/abstract_controller_execution.launch ")
add_test(_ctest_mbf_abstract_nav_rostest_test_abstract_planner_execution.launch "/home/gyc/match_ws/build_isolated/mbf_abstract_nav/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/gyc/match_ws/build_isolated/mbf_abstract_nav/test_results/mbf_abstract_nav/rostest-test_abstract_planner_execution.xml" "--return-code" "/usr/bin/python2 /opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/gyc/match_ws/src/navigation/move_base_flex/mbf_abstract_nav --package=mbf_abstract_nav --results-filename test_abstract_planner_execution.xml --results-base-dir \"/home/gyc/match_ws/build_isolated/mbf_abstract_nav/test_results\" /home/gyc/match_ws/src/navigation/move_base_flex/mbf_abstract_nav/test/abstract_planner_execution.launch ")
add_test(_ctest_mbf_abstract_nav_rostest_test_planner_action.launch "/home/gyc/match_ws/build_isolated/mbf_abstract_nav/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/gyc/match_ws/build_isolated/mbf_abstract_nav/test_results/mbf_abstract_nav/rostest-test_planner_action.xml" "--return-code" "/usr/bin/python2 /opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/gyc/match_ws/src/navigation/move_base_flex/mbf_abstract_nav --package=mbf_abstract_nav --results-filename test_planner_action.xml --results-base-dir \"/home/gyc/match_ws/build_isolated/mbf_abstract_nav/test_results\" /home/gyc/match_ws/src/navigation/move_base_flex/mbf_abstract_nav/test/planner_action.launch ")
subdirs("gtest")
